<a href="https://colab.research.google.com/github/CarlosBIOS/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://wallpapers.com/images/high/4k-tech-acbb4nkybiijedhg.webp'>

In this book, we're going to cover some of the most fundamental concepts of ***tensors*** using ***TensorFlow***

More especificaly, we're going to cover:


*   Introduction to tensors
*   Getting information from tensors
*   Manipulating tensors
*   Tensors & NumPy
*   Using @tf.function(a way to speed up your regular python funtions)
*   Using GPUs with TensorFlow( or TPUs)
*   Exercises to try for yourself!

***What is TensorFlow?***

[TensorFlow](https://www.tensorflow.org/?hl=pt) is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

# Import statements

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)
import tensorflow_probability as tfp
import numpy as np

2.17.0


# Introduction to tensors

In [ ]:
# Create tensors immutable with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the numbers of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimensions of our vector
vector.ndim

1

In [ ]:
# Create a matrix(matrix has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# check the dimensions of our vector
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)  # Specify the data type
# Escrever 16 <32, vai gastar menos espaço, pois não vai ser tão preciso
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# what's the number of dimensions
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor
# Então basicamente o shape diz-nos sempre o número de elementos de um conjunto de elementos, e se tiver um conjunto de elemento doutro conjunto de elementos, o
# proximo valor do shape vai ser o número de elementos desse mesmo, e assim por adiante!!!

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

<hr>

What we've created so far:
*   **Scalar**: a single number
*   **Vector**: a number with direction
*   **Matrix**: a 2-dimensional array of numbers
*   **Tensor**: a n-dimensional array of numbers, onde n ≥ 0

# Creating tensors with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in your changeable_tensor
changeable_tensor[0]  # <tf.Tensor: shape=(), dtype=int32, numpy=10> -> valor 10
changeable_tensor[0].assign(7)

changeable_tensor #  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)> -> valor 7

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

✅***Atenção***: Quando criamos um Tensor with Variable, torna-se um tensor mutável, mas se fizermos com constant, torna-se um tensor

# Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

Why would you want to create random tensors?

This is what neural networks use to initialize their weights (patterns) that they're trying to learn in the data.

For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

In [ ]:
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))  # normal-> normal distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

from_seed(42) -> Set seed for reproducibility. Isso significa que, ao usar a mesma semente(seed), você obterá a mesma sequência de números aleatórios em diferentes execuções do código. Isso é fundamental em machine learning e deep learning para garantir que os experimentos possam ser replicados com precisão.

In [ ]:
# Create two random(but the same) tensors
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))   # normal, pois quero uma distribuição normal
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_1

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10,7],[3,4],[2,5], [1, 6]])
not_shuffled.ndim

2

In [ ]:
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  6],
       [ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

**Exercice**: Read through TensorFlow documentation on random <a href='https://www.tensorflow.org/api_docs/python/tf/random/set_seed'> set_seed</a> generation and practise writing 5 random tensors and shufle them

In [ ]:
scalar = tf.constant(1)
tf.random.shuffle(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
vector = tf.Variable([1, 2, 3, 4, 5, 6])
tf.random.shuffle(vector)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 6, 1, 2, 5, 3], dtype=int32)>

In [ ]:
matrix = tf.constant([[1,2,4], [3,4,5], [6,7,8]])
tf.random.shuffle(matrix, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 7, 8],
       [3, 4, 5],
       [1, 2, 4]], dtype=int32)>

In [ ]:
matrix = tf.Variable([[[1,2,3], [11,23,32]], [[1,2,3], [4,5,6]], [[7,8,9], [1290,29103,2190]]])
tf.random.shuffle(matrix)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[    1,     2,     3],
        [    4,     5,     6]],

       [[    1,     2,     3],
        [   11,    23,    32]],

       [[    7,     8,     9],
        [ 1290, 29103,  2190]]], dtype=int32)>

# Other way to create Tensors

> *tf.ones([l, c])* -> create a tensor with l linhas e c colunas. Todos os elementos é o número 1

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.ones([10,7], dtype=tf.int32)

<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

> tf.zeros([l, c]) -> Cria um tensor com l linhas e c colunas. Todos os elementos são nulos

In [ ]:
# P1:
tf.zeros([3,4])
# P2:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.eye(3, dtype=tf.int32)  # cria uma matriz identidade

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

##  Turn Numpy arrays into tensors

The main difference between NumPy arrays e Tensorflow tensors is that tensors can be run on a GPU(much faster for numerical computing)

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)  # create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))  # basicamente, fez 4!=4*3*2=24, mas existe outras maneiras, por exemplo, 8*3=24
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors

* Shape -> The **length** (number of elements) of each of the dimensions of a tensor. -> *tensor.shape*
* Rank -> The **number of tensor dimension**s. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. -> *tensor.ndim*
* Axis or Dimensions -> A particular **dimension** of a tensor. -> *tensor[0], tensor[:, 1]…*
* Size -> The total **number of items** in the tensor -> *tf.size(tensor)*

In [ ]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.shape, A.ndim, A[0][0], tf.size(A).numpy()

(TensorShape([2, 3, 4]),
 3,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 24)

In [ ]:
# Create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5=5!):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5=5!): 120


# Indexing Tensors

Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim, rank_2_tensor.numpy(), tf.size(rank_2_tensor).numpy()

(TensorShape([2, 2]),
 2,
 array([[10,  7],
        [ 3,  4]], dtype=int32),
 4)

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimensions to our rank 2 tensor
# P1:
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
# P2:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor, rank_3_tensor.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>,
 3)

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)  # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)  # expand the 1-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

> 🔑 **Nota**: Como dá para reparar, o tensor original nunca foi alterado e sim, estamos a criar tensors novos sem mudar o tensor original!!!

# Manipulating tensors (tensors operations)

**Basic Operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
print(tensor + 10)
# The original tensor is unchanged
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10), tf.add(tensor, 10), tf.subtract(tensor, 10), tf.divide(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

# Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations

TensorFlow implements this matrix multiplication functionality in the `tf.matmul()` method.

1. The inner dimensions must match:
* (3, 5) @ (3, 5) won't work
* (3, 3) @ (3, 3) will work
* (5, 3) @ (3, 5) will work
* (3, 5) @ (5, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
* (5, 3) @ (3, 5) -> (5, 5)
* (3, 5) @ (5, 3) -> (3, 3)

> 🔑 Note: '@' in Python is the symbol for matrix multiplication

In [ ]:
# P1:
tf.matmul(tensor, tensor)
# P2:
tensor, tensor @ tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [ ]:
# Create a tensor (3, 2)
X = tf.constant([[1,2],[3,4],[5,6]])
# Create another (3, 2) tensor
Y = tf.constant([[7,8],[9,10],[11,12]])
X, Y
# E se tentar multiplicar, logicamente vai dar erro, pois estão a multiplicar 3 rows com 2 columns

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Lets change the shape of Y
Y_reshape = tf.reshape(Y, shape=(2,3))

In [ ]:
X @ Y_reshape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# You can do the same with transpose
tf.transpose(X), tf.reshape(X, shape=(2,3)), X

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

* `reshape` ➡ A ordem é pelas linhas
* `transpose` ➡ A ordem é pelas colunas

# Changing the datatype of a tensor

In [ ]:
B = tf.constant([1.7, 7.4])
B.dtype, B

(tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16(reduzir precisão, mas fica mais leve)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

> `cast` ➡ Serve para alterar a datatype

In [ ]:
tf.cast(B, dtype=tf.int32)
# Se quero colocar float to int, ele não vai arrendodar e só fica com as unidades

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

# Aggregation Tensors

Aggregation tensors = condensing them from multiple values down to a smaller amount of value.

Let's go throught the following forms of aggregation:

* Get the abs of a tensor ➡ `tf.abs(tensor)`
* Get the minimum ➡ `tf.reduce_min(tensor)`
* Get the maximum ➡ `tf.reduce_max(tensor)`
* Get the mean of a tensor ➡ `tf.reduce_mean(tensor)`
* Get the sum of a tensor ➡ `tf.reduce_sum(tensor)`
* Get the standard deviation of a tensor ➡ `tf.math.reduce_std(tensor)`
* Get the variance of a tensor ➡ `tf.math.reduce_variance(tensor)`

## Get the absolute values

In [ ]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

> `abs` ➡ Torna um tensor, onde esse tensor só tem elementos positivos


## The rest of information

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 60, 96,  7, 35, 59, 25, 12, 76,  8, 27, 66, 75, 21,  2,  9, 65,
       19, 54, 45, 10, 61, 33, 56, 12, 70, 86, 85, 67, 24, 12, 17, 41, 12,
       43, 59, 61, 92, 25,  5, 24, 11, 71, 90, 48, 45, 34, 15, 44, 46])>

In [ ]:
# Find the minimum
E_min = tf.reduce_min(E)
E_min

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Find the maximum
E_max = tf.reduce_max(E)
E_max

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
# Find the mean
E_mean = tf.reduce_mean(E)
E_mean

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [ ]:
# Find the sum of elements
E_sum = tf.reduce_sum(E)
E_sum

<tf.Tensor: shape=(), dtype=int64, numpy=2092>

In [ ]:
# Get the standard deviation
E_std = tf.math.reduce_std(tf.cast(E, dtype=tf.float32))
E_std

<tf.Tensor: shape=(), dtype=float32, numpy=26.546833>

In [ ]:
# Get the variance
# P1:
E_var = tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))
# P2
# import tensorflow_probability as tfp
E_var2 = tfp.stats.variance(E)

E_var2, E_var

(<tf.Tensor: shape=(), dtype=int64, numpy=705>,
 <tf.Tensor: shape=(), dtype=float32, numpy=704.7344>)

# Find the position maximum and minimum

How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say `['Green', 'Blue', 'Red']`) with your prediction probabilities tensor (e.g. `[0.98, 0.01, 0.01]`).

In this case, the predicted label (the one with the highest prediction probability) would be `'Green'`.

You can do the same for the minimum (if required) with the following:

* tf.argmax() - find the position of the maximum element in a given tensor.
* tf.argmin() - find the position of the minimum element in a given tensor.

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)  # dá o index

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)].numpy()

0.9671384

In [ ]:
# Find the maximum value of F and check for equality
tf.reduce_max(F).numpy(), F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()

(0.9671384, True)

In [ ]:
# Find the positional minimum
tf.argmin(F)  # dá o index

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Index on our lowest value position
F[tf.argmin(F)].numpy()

0.009463668

In [ ]:
# Find the minimum value of F and check for equality
tf.reduce_min(F).numpy(), F[tf.argmin(F)].numpy() == tf.reduce_min(F).numpy()

(0.009463668, True)

# Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]  # could be red, blue, green and purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'Yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'Yo I love deep learning']],
      dtype=object)>

# Squaring, log, square root

* `tf.square(tensor)` ➡ Calcula todos os elementos ao quadrado no tensor
* `tf.sqrt(tensor)` ➡ Calcula a raíz quadrado do tensor
* `tf.log(tensor)` ➡ Calcula a log de um tensor

In [ ]:
# Create a new tensor
H = tf.range(1, 10)

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the squareroot
tf.sqrt(tf.cast(H, dtype=tf.float32)), tf.sqrt(tf.cast(tf.square(H), dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>)

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and NumPy

We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

* `np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype).
* `tensor.numpy()` - call on a tensor to convert to an ndarray.

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

> 🔑**Note**: One of the main difference between a TensorFlow and NumPy array is that a TensorFlow tensor can be run on a TPU(tensor processing unit) or GPU (for faster numerical processing)

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Sep 21 10:05:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Exercices:

* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
* Find the shape, rank and size of the tensors you created in 1.
* Create two tensors containing random values between 0 and 1 with shape [5, 300].
* Multiply the two tensors you created in 3 using matrix multiplication.
* Multiply the two tensors you created in 3 using dot product.
* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
* Find the min and max values of the tensor you created in 6.
* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
* One-hot encode the tensor you created in 9.

## 1:

In [ ]:
scalar = tf.constant(7)
vector = tf.constant([1, 2])
matrix = tf.constant([[1, 2], [3, 4]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

## 2

In [ ]:
scalar.shape, scalar.ndim, tf.size(scalar).numpy()

(TensorShape([]), 0, 1)

In [ ]:
vector.shape, vector.ndim, tf.size(vector).numpy()

(TensorShape([2]), 1, 2)

In [ ]:
matrix.shape, matrix.ndim, tf.size(matrix).numpy()

(TensorShape([2, 2]), 2, 4)

In [ ]:
tensor.shape, tensor.ndim, tf.size(tensor).numpy()

(TensorShape([2, 2, 2]), 3, 8)

## 3

In [ ]:
# Não posso usar a distribuição normal, pois vai ter valores negativos
random_A = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)
random_B = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)
random_A, random_B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.3572563 , 0.32546926, 0.9001672 , ..., 0.08959854, 0.01839232,
         0.2335    ],
        [0.82871616, 0.532145  , 0.01331937, ..., 0.82246876, 0.17526948,
         0.13115883],
        [0.65760195, 0.02555394, 0.0109899 , ..., 0.6935954 , 0.92843163,
         0.8634182 ],
        [0.7003875 , 0.01071537, 0.8189659 , ..., 0.8491818 , 0.8331547 ,
         0.6535715 ],
        [0.830132  , 0.4387324 , 0.907568  , ..., 0.6718364 , 0.95745873,
         0.14117885]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5852475 , 0.9927181 , 0.3110503 , ..., 0.224841  , 0.49989998,
         0.6593435 ],
        [0.17314231, 0.8545804 , 0.0195756 , ..., 0.93596196, 0.6465831 ,
         0.6386726 ],
        [0.9803549 , 0.06948674, 0.32655454, ..., 0.18921721, 0.20934463,
         0.7273139 ],
        [0.38395214, 0.254923  , 0.93402433, ..., 0.01896858, 0.5011966 ,
         0.14013577],
        [0.03561

## 4

In [ ]:
random_A @ tf.transpose(random_B)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-5.7330256, -7.479598 , -1.1431093, -8.01188  , -1.6717486],
       [12.607795 , 14.794084 , -1.1767391, 15.987692 , 10.253158 ],
       [10.903134 ,  5.962957 , 16.11954  , 10.906892 ,  4.4060946],
       [-9.317261 , -2.540908 , -2.0218508,  3.9004316, -3.2297082],
       [21.306767 , 10.802096 , 13.624947 , 12.4881315, 15.830592 ]],
      dtype=float32)>

## 5

In [ ]:

tf.tensordot(random_A, tf.transpose(random_B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-5.7330256, -7.479598 , -1.1431093, -8.01188  , -1.6717486],
       [12.607795 , 14.794084 , -1.1767391, 15.987692 , 10.253158 ],
       [10.903134 ,  5.962957 , 16.11954  , 10.906892 ,  4.4060946],
       [-9.317261 , -2.540908 , -2.0218508,  3.9004316, -3.2297082],
       [21.306767 , 10.802096 , 13.624947 , 12.4881315, 15.830592 ]],
      dtype=float32)>

## 6

In [ ]:
random_C = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
random_C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95171106, 0.12621379, 0.04421461],
        [0.3843361 , 0.970186  , 0.8468393 ],
        [0.11516833, 0.21383655, 0.94459426],
        ...,
        [0.86352444, 0.40930748, 0.833953  ],
        [0.10420096, 0.360116  , 0.41648877],
        [0.5491947 , 0.24029827, 0.78714883]],

       [[0.76900077, 0.76130474, 0.19085038],
        [0.9853723 , 0.00754154, 0.44409752],
        [0.23491156, 0.45407653, 0.13934505],
        ...,
        [0.754087  , 0.9222647 , 0.16887152],
        [0.6965729 , 0.4035406 , 0.74383795],
        [0.23956501, 0.36897278, 0.64913917]],

       [[0.69961846, 0.9332825 , 0.25744224],
        [0.14831996, 0.45024633, 0.33792293],
        [0.37361288, 0.52841246, 0.55880976],
        ...,
        [0.18407178, 0.30312943, 0.06171513],
        [0.53060853, 0.17844844, 0.9650723 ],
        [0.7102839 , 0.4532268 , 0.49193168]],

       ...,

       [[0.34682655, 0.72270703, 0.863091  ],
        [0.99

## 7

In [ ]:
tf.reduce_min(random_C), tf.reduce_max(random_C)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.2874603e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999999>)

## 8

In [ ]:
random_D = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
tf.squeeze(random_D).shape

TensorShape([224, 224, 3])

## 9

In [ ]:
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])
tf.argmax(ten_tensor).numpy(), tf.argmin(ten_tensor).numpy()

(6, 8)

## 10

In [ ]:
# One hot encoding the tensor of shape 10
tf.one_hot(tf.cast(ten_tensor , dtype=tf.int32) , depth = len(ten_tensor))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>